import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import CreateEventDrawer from "@/components/create-event";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={inter}
      >
        <Header />
        <Toaster
          position="bottom-right"  
          toastOptions={{
            duration: 4000, 
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />        <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
          {children}
        </main>
        <Footer />
        <CreateEventDrawer />
      </body>
    </html>
    </ClerkProvider>
  );
}
